---
- name: setup AWS infrastructure
  hosts: localhost
  gather_facts: false
  connection: local
  vars_files: local_vars
  tasks:
    - name: create cloudformation stack
      cloudformation:
        stack_name: "{{ stack_name }}"
        region: "{{ region }}"
        disable_rollback: true
        state: "{{ stack_state | default('present') }}"
        template: "main-template.yaml"
        template_parameters:
          KeyName: "{{ keypair }}"
          WebserverInstanceType: "{{ instance_type }}"
          MyIP: "{{ my_ip }}"
          VpcCidrBlock: "{{ vpc_cidr_block }}"
          Ec2CidrBlock: "{{ ec2_subnet_cidr }}"
          Rds1SubnetCidr: "{{ rds1_subnet_cidr }}"
          Rds2SubnetCidr: "{{ rds2_subnet_cidr }}"
        tags:
          stack: "{{ stack_name }}"

